(function(a){a.jgrid.extend({getColProp:function(e){var o={},b=this[0];if(b.grid){b=b.p.colModel;for(var n=0;n<b.length;n++)if(b[n].name==e){o=b[n];break}return o}},setColProp:function(e,o){return this.each(function(){if(this.grid)if(o)for(var b=this.p.colModel,n=0;n<b.length;n++)if(b[n].name==e){a.extend(this.p.colModel[n],o);break}})},sortGrid:function(e,o){return this.each(function(){var b=this,n=-1;if(b.grid){if(!e)e=b.p.sortname;for(var s=0;s<b.p.colModel.length;s++)if(b.p.colModel[s].index==
e||b.p.colModel[s].name==e){n=s;break}if(n!=-1){s=b.p.colModel[n].sortable;if(typeof s!=="boolean")s=true;if(typeof o!=="boolean")o=false;s&&b.sortData("jqgh_"+e,n,o)}}})},GridDestroy:function(){return this.each(function(){if(this.grid){this.p.pager&&a(this.p.pager).remove();var e=this.id;try{a("#gbox_"+e).remove()}catch(o){}}})},GridUnload:function(){return this.each(function(){if(this.grid){var e={id:a(this).attr("id"),cl:a(this).attr("class")};this.p.pager&&a(this.p.pager).empty().removeClass("ui-state-default ui-jqgrid-pager corner-bottom");
var o=document.createElement("table");a(o).attr({id:e.id});o.className=e.cl;e=this.id;a(o).removeClass("ui-jqgrid-btable");if(a(this.p.pager).parents("#gbox_"+e).length===1){a(o).insertBefore("#gbox_"+e).show();a(this.p.pager).insertBefore("#gbox_"+e)}else a(o).insertBefore("#gbox_"+e).show();a("#gbox_"+e).remove()}})},setGridState:function(e){return this.each(function(){if(this.grid){$t=this;if(e=="hidden"){a(".ui-jqgrid-bdiv, .ui-jqgrid-hdiv","#gview_"+$t.p.id).slideUp("fast");$t.p.pager&&a($t.p.pager).slideUp("fast");
if($t.p.toolbar[0]===true){$t.p.toolbar[1]=="both"&&a($t.grid.ubDiv).slideUp("fast");a($t.grid.uDiv).slideUp("fast")}$t.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+$s.p.id).slideUp("fast");a(".ui-jqgrid-titlebar-close span",$t.grid.cDiv).removeClass("ui-icon-circle-triangle-n").addClass("ui-icon-circle-triangle-s");$t.p.gridstate="hidden"}else if(e=="visible"){a(".ui-jqgrid-hdiv, .ui-jqgrid-bdiv","#gview_"+$t.p.id).slideDown("fast");$t.p.pager&&a($t.p.pager).slideDown("fast");if($t.p.toolbar[0]===true){$t.p.toolbar[1]==
"both"&&a($t.grid.ubDiv).slideDown("fast");a($t.grid.uDiv).slideDown("fast")}$t.p.footerrow&&a(".ui-jqgrid-sdiv","#gbox_"+$t.p.id).slideDown("fast");a(".ui-jqgrid-titlebar-close span",$t.grid.cDiv).removeClass("ui-icon-circle-triangle-s").addClass("ui-icon-circle-triangle-n");$t.p.gridstate="visible"}}})},updateGridRows:function(e,o,b){var n,s=false;this.each(function(){var r=this,l,j,t,g;if(!r.grid)return false;o||(o="id");e&&e.length>0&&a(e).each(function(){t=this;if(j=r.rows.namedItem(t[o])){g=
t[o];if(b===true)if(r.p.jsonReader.repeatitems===true){if(r.p.jsonReader.cell)t=t[r.p.jsonReader.cell];for(var d=0;d<t.length;d++){l=r.formatter(g,t[d],d,t,"edit");r.p.treeGrid===true&&n==r.p.ExpandColumn?a("td:eq("+d+") > span:first",j).html(l).attr("title",a.jgrid.stripHtml(l)):a("td:eq("+d+")",j).html(l).attr("title",a.jgrid.stripHtml(l))}return s=true}a(r.p.colModel).each(function(c){n=b===true?this.jsonmap||this.name:this.name;if(t[n]!=undefined){l=r.formatter(g,t[n],c,t,"edit");r.p.treeGrid===
true&&n==r.p.ExpandColumn?a("td:eq("+c+") > span:first",j).html(l).attr("title",a.jgrid.stripHtml(l)):a("td:eq("+c+")",j).html(l).attr("title",a.jgrid.stripHtml(l));s=true}})}})});return s},filterGrid:function(e,o){o=a.extend({gridModel:false,gridNames:false,gridToolbar:false,filterModel:[],formtype:"horizontal",autosearch:true,formclass:"filterform",tableclass:"filtertable",buttonclass:"filterbutton",searchButton:"Search",clearButton:"Clear",enableSearch:false,enableClear:false,beforeSearch:null,
afterSearch:null,beforeClear:null,afterClear:null,url:"",marksearched:true},o||{});return this.each(function(){var b=this;this.p=o;if(this.p.filterModel.length==0&&this.p.gridModel===false)alert("No filter is set");else if(e){this.p.gridid=e.indexOf("#")!=-1?e:"#"+e;var n=a(this.p.gridid).jqGrid("getGridParam","colModel");if(n){if(this.p.gridModel===true){var s=a(this.p.gridid)[0],r;a.each(n,function(d){var c=[];this.search=this.search===false?false:true;r=this.editrules&&this.editrules.searchhidden===
true?true:this.hidden===true?false:true;if(this.search===true&&r===true){c.label=b.p.gridNames===true?s.p.colNames[d]:"";c.name=this.name;c.index=this.index||this.name;c.stype=this.edittype||"text";if(c.stype!="select")c.stype="text";c.defval=this.defval||"";c.surl=this.surl||"";c.sopt=this.editoptions||{};c.width=this.width;b.p.filterModel.push(c)}})}else a.each(b.p.filterModel,function(){for(var d=0;d<n.length;d++)if(this.name==n[d].name){this.index=n[d].index||this.name;break}if(!this.index)this.index=
this.name});var l=function(){var d={},c=0,m,f=a(b.p.gridid)[0],h;f.p.searchdata={};a.isFunction(b.p.beforeSearch)&&b.p.beforeSearch();a.each(b.p.filterModel,function(){h=this.index;switch(this.stype){case "select":if(m=a("select[name="+h+"]",b).val()){d[h]=m;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");c++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(p){}}break;default:if(m=a("input[name="+
h+"]",b).val()){d[h]=m;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");c++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(u){}}}});var k=c>0?true:false;a.extend(f.p.postData,d);var i;if(b.p.url){i=a(f).jqGrid("getGridParam","url");a(f).jqGrid("setGridParam",{url:b.p.url})}a(f).jqGrid("setGridParam",{search:k}).trigger("reloadGrid",[{page:1}]);i&&a(f).jqGrid("setGridParam",{url:i});a.isFunction(b.p.afterSearch)&&
b.p.afterSearch()},j=function(){var d={},c,m=0,f=a(b.p.gridid)[0],h;a.isFunction(b.p.beforeClear)&&b.p.beforeClear();a.each(b.p.filterModel,function(){h=this.index;c=this.defval?this.defval:"";switch(this.stype){case "select":var p;a("select[name="+h+"] option",b).each(function(v){if(v==0)this.selected=true;if(a(this).text()==c){this.selected=true;p=a(this).val();return false}});if(p){d[h]=p;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");m++}else{b.p.marksearched&&a("#jqgh_"+
this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(u){}}break;case "text":a("input[name="+h+"]",b).val(c);if(c){d[h]=c;b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).addClass("dirty-cell");m++}else{b.p.marksearched&&a("#jqgh_"+this.name,f.grid.hDiv).removeClass("dirty-cell");try{delete f.p.postData[this.index]}catch(q){}}break}});var k=m>0?true:false;a.extend(f.p.postData,d);var i;if(b.p.url){i=a(f).jqGrid("getGridParam","url");a(f).jqGrid("setGridParam",
{url:b.p.url})}a(f).jqGrid("setGridParam",{search:k}).trigger("reloadGrid",[{page:1}]);i&&a(f).jqGrid("setGridParam",{url:i});a.isFunction(b.p.afterClear)&&b.p.afterClear()},t=a("<form name='SearchForm' style=display:inline;' class='"+this.p.formclass+"'></form>"),g=a("<table class='"+this.p.tableclass+"' cellspacing='0' cellpading='0' border='0'><tbody></tbody></table>");a(t).append(g);(function(){var d=document.createElement("tr"),c,m,f,h;b.p.formtype=="horizontal"&&a(g).append(d);a.each(b.p.filterModel,
function(k){f=document.createElement("td");a(f).append("<label for='"+this.name+"'>"+this.label+"</label>");h=document.createElement("td");var i=this;if(!this.stype)this.stype="text";switch(this.stype){case "select":if(this.surl)a(h).load(this.surl,function(){i.defval&&a("select",this).val(i.defval);a("select",this).attr({name:i.index||i.name,id:"sg_"+i.name});i.sopt&&a("select",this).attr(i.sopt);b.p.gridToolbar===true&&i.width&&a("select",this).width(i.width);b.p.autosearch===true&&a("select",this).change(function(){l();
return false})});else if(i.sopt.value){var p=i.sopt.value,u=document.createElement("select");a(u).attr({name:i.index||i.name,id:"sg_"+i.name}).attr(i.sopt);if(typeof p==="string"){k=p.split(";");for(var q,v=0;v<k.length;v++){p=k[v].split(":");q=document.createElement("option");q.value=p[0];q.innerHTML=p[1];if(p[1]==i.defval)q.selected="selected";u.appendChild(q)}}else if(typeof p==="object")for(v in p){k++;q=document.createElement("option");q.value=v;q.innerHTML=p[v];if(p[v]==i.defval)q.selected=
"selected";u.appendChild(q)}b.p.gridToolbar===true&&i.width&&a(u).width(i.width);a(h).append(u);b.p.autosearch===true&&a(u).change(function(){l();return false})}break;case "text":u=this.defval?this.defval:"";a(h).append("<input type='text' name='"+(this.index||this.name)+"' id='sg_"+this.name+"' value='"+u+"'/>");i.sopt&&a("input",h).attr(i.sopt);if(b.p.gridToolbar===true&&i.width)a.browser.msie?a("input",h).width(i.width-4):a("input",h).width(i.width-2);b.p.autosearch===true&&a("input",h).keypress(function(w){if((w.charCode?
w.charCode:w.keyCode?w.keyCode:0)==13){l();return false}return this});break}if(b.p.formtype=="horizontal"){b.p.gridToolbar===true&&b.p.gridNames===false?a(d).append(h):a(d).append(f).append(h);a(d).append(h)}else{c=document.createElement("tr");a(c).append(f).append(h);a(g).append(c)}});h=document.createElement("td");if(b.p.enableSearch===true){m="<input type='button' id='sButton' class='"+b.p.buttonclass+"' value='"+b.p.searchButton+"'/>";a(h).append(m);a("input#sButton",h).click(function(){l();return false})}if(b.p.enableClear===
true){m="<input type='button' id='cButton' class='"+b.p.buttonclass+"' value='"+b.p.clearButton+"'/>";a(h).append(m);a("input#cButton",h).click(function(){j();return false})}if(b.p.enableClear===true||b.p.enableSearch===true)if(b.p.formtype=="horizontal")a(d).append(h);else{c=document.createElement("tr");a(c).append("<td>&#160;</td>").append(h);a(g).append(c)}})();a(this).append(t);this.triggerSearch=l;this.clearSearch=j}else alert("Could not get grid colModel")}else alert("No target grid is set!")})},
filterToolbar:function(e){e=a.extend({autosearch:true,searchOnEnter:false,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,searchurl:"",stringResult:false,groupOp:"AND"},e||{});return this.each(function(){function o(g,d){var c=a(g);c[0]!=null&&jQuery.each(d,function(){this.data!=null?c.bind(this.type,this.data,this.fn):c.bind(this.type,this.fn)})}var b=this,n=function(){var g={},d=0,c,m,f={};a.each(b.p.colModel,function(){m=this.index||this.name;var q=this.searchoptions&&this.searchoptions.sopt?
this.searchoptions.sopt[0]:"eq";switch(this.stype){case "select":if(c=a("select[name="+m+"]",b.grid.hDiv).val()){g[m]=c;f[m]=q;d++}else try{delete b.p.postData[m]}catch(v){}break;case "text":if(c=a("input[name="+m+"]",b.grid.hDiv).val()){g[m]=c;f[m]=q;d++}else try{delete b.p.postData[m]}catch(w){}break}});var h=d>0?true:false;if(e.stringResult){var k='{"groupOp":"'+e.groupOp+'","rules":[',i=0;a.each(g,function(q,v){if(i>0)k+=",";k+='{"field":"'+q+'",';k+='"op":"'+f[q]+'",';k+='"data":"'+v+'"}';i++});
k+="]}";a.extend(b.p.postData,{filters:k})}else a.extend(b.p.postData,g);var p;if(b.p.searchurl){p=b.p.url;a(b).jqGrid("setGridParam",{url:b.p.searchurl})}var u=false;if(a.isFunction(e.beforeSearch))u=e.beforeSearch.call(b);u||a(b).jqGrid("setGridParam",{search:h}).trigger("reloadGrid",[{page:1}]);p&&a(b).jqGrid("setGridParam",{url:p});a.isFunction(e.afterSearch)&&e.afterSearch()},s=a("<tr class='ui-search-toolbar' role='rowheader'></tr>"),r,l,j,t;a.each(b.p.colModel,function(){var g=this;r=a("<th role='columnheader' class='ui-state-default ui-th-column ui-th-"+
b.p.direction+"'></th>");l=a("<div style='width:100%;position:relative;height:100%;padding-right:0.3em;'></div>");this.hidden===true&&a(r).css("display","none");this.search=this.search===false?false:true;if(typeof this.stype=="undefined")this.stype="text";j=a.extend({},this.searchoptions||{});if(this.search)switch(this.stype){case "select":var d=this.surl||j.dataUrl;if(d)a.ajax(a.extend({url:d,dataType:"html",complete:function(k){if(j.buildSelect!=null)(k=j.buildSelect(k))&&a(l).append(k);else a(l).append(k.responseText);
j.defaultValue&&a("select",l).val(j.defaultValue);a("select",l).attr({name:g.index||g.name,id:"gs_"+g.name});j.attr&&a("select",l).attr(j.attr);a("select",l).css({width:"100%"});j.dataInit!=null&&j.dataInit(a("select",l)[0]);j.dataEvents!=null&&o(a("select",l)[0],j.dataEvents);e.autosearch===true&&a("select",l).change(function(){n();return false})}},a.jgrid.ajaxOptions,b.p.ajaxSelectOptions||{}));else{var c;if(g.searchoptions&&g.searchoptions.value)c=g.searchoptions.value;else if(g.editoptions&&g.editoptions.value)c=
g.editoptions.value;if(c){d=document.createElement("select");d.style.width="100%";a(d).attr({name:g.index||g.name,id:"gs_"+g.name});if(typeof c==="string"){c=c.split(";");for(var m,f,h=0;h<c.length;h++){m=c[h].split(":");f=document.createElement("option");f.value=m[0];f.innerHTML=m[1];d.appendChild(f)}}else if(typeof c==="object")for(m in c){f=document.createElement("option");f.value=m;f.innerHTML=c[m];d.appendChild(f)}j.defaultValue&&a(d).val(j.defaultValue);j.attr&&a(d).attr(j.attr);j.dataInit!=
null&&j.dataInit(d);j.dataEvents!=null&&o(d,j.dataEvents);a(l).append(d);e.autosearch===true&&a(d).change(function(){n();return false})}}break;case "text":d=j.defaultValue?j.defaultValue:"";a(l).append("<input type='text' style='width:95%;padding:0px;' name='"+(g.index||g.name)+"' id='gs_"+g.name+"' value='"+d+"'/>");j.attr&&a("input",l).attr(j.attr);j.dataInit!=null&&j.dataInit(a("input",l)[0]);j.dataEvents!=null&&o(a("input",l)[0],j.dataEvents);if(e.autosearch===true)e.searchOnEnter?a("input",l).keypress(function(k){if((k.charCode?
k.charCode:k.keyCode?k.keyCode:0)==13){n();return false}return this}):a("input",l).keydown(function(k){k=k.which;if(k!=9&&k!=16){t&&clearTimeout(t);t=setTimeout(function(){n()},500)}});break}a(r).append(l);a(s).append(r)});a("table thead",b.grid.hDiv).append(s);this.triggerToolbar=n;this.clearToolbar=function(g){var d={},c,m=0,f;g=typeof g!="boolean"?true:g;a.each(b.p.colModel,function(){c=this.searchoptions&&this.searchoptions.defaultValue?this.searchoptions.defaultValue:"";f=this.index||this.name;
switch(this.stype){case "select":var q;a("select[name="+f+"] option",b.grid.hDiv).each(function(x){if(x==0)this.selected=true;if(a(this).text()==c){this.selected=true;q=a(this).val();return false}});if(q){d[f]=q;m++}else try{delete b.p.postData[f]}catch(v){}break;case "text":a("input[name="+f+"]",b.grid.hDiv).val(c);if(c){d[f]=c;m++}else try{delete b.p.postData[f]}catch(w){}break}});var h=m>0?true:false;if(e.stringResult){var k='{"groupOp":"'+e.groupOp+'","rules":[',i=0;a.each(d,function(q,v){if(i>
0)k+=",";k+='{"field":"'+q+'",';k+='"op":"eq",';k+='"data":"'+v+'"}';i++});k+="]}";a.extend(b.p.postData,{filters:k})}else a.extend(b.p.postData,d);var p;if(b.p.searchurl){p=b.p.url;a(b).jqGrid("setGridParam",{url:b.p.searchurl})}var u=false;if(a.isFunction(e.beforeClear))u=e.beforeClear.call(b);u||g&&a(b).jqGrid("setGridParam",{search:h}).trigger("reloadGrid",[{page:1}]);p&&a(b).jqGrid("setGridParam",{url:p});a.isFunction(e.afterClear)&&e.afterClear()};this.toggleToolbar=function(){var g=a("tr.ui-search-toolbar",
b.grid.hDiv);g.css("display")=="none"?g.show():g.hide()}})}})})(jQuery);
