(function(c){c.uniform={options:{selectClass:"selector",radioClass:"radio",checkboxClass:"checker",fileClass:"uploader",filenameClass:"filename",fileBtnClass:"action",fileDefaultText:"No file selected",fileBtnText:"Choose File",checkedClass:"checked",focusClass:"focus",disabledClass:"disabled",buttonClass:"button",activeClass:"active",hoverClass:"hover",useID:true,idPrefix:"uniform",resetSelector:false,autoHide:true},elements:[]};c.support.selectOpacity=c.browser.msie&&c.browser.version<7?false:true;
c.fn.uniform=function(a){function l(b){$el=c(b);$el.addClass($el.attr("type"));i(b)}function m(b){c(b).addClass("uniform");i(b)}function n(b){var e=c(b),d=c("<div>"),f=c("<span>");d.addClass(a.buttonClass);a.useID&&e.attr("id")!=""&&d.attr("id",a.idPrefix+"-"+e.attr("id"));var g;if(e.is("a")||e.is("button"))g=e.text();else if(e.is(":submit")||e.is(":reset")||e.is("input[type=button]"))g=e.attr("value");g=g==""?e.is(":reset")?"Reset":"Submit":g;f.html(g);e.css("opacity",0);e.wrap(d);e.wrap(f);d=e.closest("div");
f=e.closest("span");e.is(":disabled")&&d.addClass(a.disabledClass);d.bind({"mouseenter.uniform":function(){d.addClass(a.hoverClass)},"mouseleave.uniform":function(){d.removeClass(a.hoverClass);d.removeClass(a.activeClass)},"mousedown.uniform touchbegin.uniform":function(){d.addClass(a.activeClass)},"mouseup.uniform touchend.uniform":function(){d.removeClass(a.activeClass)},"click.uniform touchend.uniform":function(j){if(c(j.target).is("span")||c(j.target).is("div"))if(b[0].dispatchEvent){j=document.createEvent("MouseEvents");
j.initEvent("click",true,true);b[0].dispatchEvent(j)}else b[0].click()}});b.bind({"focus.uniform":function(){d.addClass(a.focusClass)},"blur.uniform":function(){d.removeClass(a.focusClass)}});c.uniform.noSelect(d);i(b)}function o(b){var e=c(b),d=c("<div />"),f=c("<span />");!e.css("display")=="none"&&a.autoHide&&d.hide();d.addClass(a.selectClass);a.useID&&b.attr("id")!=""&&d.attr("id",a.idPrefix+"-"+b.attr("id"));e=b.find(":selected:first");if(e.length==0)e=b.find("option:first");f.html(e.html());
b.css("opacity",0);b.wrap(d);b.before(f);d=b.parent("div");f=b.siblings("span");b.bind({"change.uniform":function(){f.text(b.find(":selected").html());d.removeClass(a.activeClass)},"focus.uniform":function(){d.addClass(a.focusClass)},"blur.uniform":function(){d.removeClass(a.focusClass);d.removeClass(a.activeClass)},"mousedown.uniform touchbegin.uniform":function(){d.addClass(a.activeClass)},"mouseup.uniform touchend.uniform":function(){d.removeClass(a.activeClass)},"click.uniform touchend.uniform":function(){d.removeClass(a.activeClass)},
"mouseenter.uniform":function(){d.addClass(a.hoverClass)},"mouseleave.uniform":function(){d.removeClass(a.hoverClass);d.removeClass(a.activeClass)},"keyup.uniform":function(){f.text(b.find(":selected").html())}});c(b).attr("disabled")&&d.addClass(a.disabledClass);c.uniform.noSelect(f);i(b)}function p(b){var e=c(b),d=c("<div />"),f=c("<span />");!e.css("display")=="none"&&a.autoHide&&d.hide();d.addClass(a.checkboxClass);a.useID&&b.attr("id")!=""&&d.attr("id",a.idPrefix+"-"+b.attr("id"));c(b).wrap(d);
c(b).wrap(f);f=b.parent();d=f.parent();c(b).css("opacity",0).bind({"focus.uniform":function(){d.addClass(a.focusClass)},"blur.uniform":function(){d.removeClass(a.focusClass)},"click.uniform touchend.uniform":function(){c(b).attr("checked")?f.addClass(a.checkedClass):f.removeClass(a.checkedClass)},"mousedown.uniform touchbegin.uniform":function(){d.addClass(a.activeClass)},"mouseup.uniform touchend.uniform":function(){d.removeClass(a.activeClass)},"mouseenter.uniform":function(){d.addClass(a.hoverClass)},
"mouseleave.uniform":function(){d.removeClass(a.hoverClass);d.removeClass(a.activeClass)}});c(b).attr("checked")&&f.addClass(a.checkedClass);c(b).attr("disabled")&&d.addClass(a.disabledClass);i(b)}function q(b){var e=c(b),d=c("<div />"),f=c("<span />");!e.css("display")=="none"&&a.autoHide&&d.hide();d.addClass(a.radioClass);a.useID&&b.attr("id")!=""&&d.attr("id",a.idPrefix+"-"+b.attr("id"));c(b).wrap(d);c(b).wrap(f);f=b.parent();d=f.parent();c(b).css("opacity",0).bind({"focus.uniform":function(){d.addClass(a.focusClass)},
"blur.uniform":function(){d.removeClass(a.focusClass)},"click.uniform touchend.uniform":function(){if(c(b).attr("checked")){var g=a.radioClass.split(" ")[0];c("."+g+" span."+a.checkedClass+":has([name='"+c(b).attr("name")+"'])").removeClass(a.checkedClass);f.addClass(a.checkedClass)}else f.removeClass(a.checkedClass)},"mousedown.uniform touchend.uniform":function(){c(b).is(":disabled")||d.addClass(a.activeClass)},"mouseup.uniform touchbegin.uniform":function(){d.removeClass(a.activeClass)},"mouseenter.uniform touchend.uniform":function(){d.addClass(a.hoverClass)},
"mouseleave.uniform":function(){d.removeClass(a.hoverClass);d.removeClass(a.activeClass)}});c(b).attr("checked")&&f.addClass(a.checkedClass);c(b).attr("disabled")&&d.addClass(a.disabledClass);i(b)}function r(b){var e=c(b),d=c("<div />"),f=c("<span>"+a.fileDefaultText+"</span>"),g=c("<span>"+a.fileBtnText+"</span>");!e.css("display")=="none"&&a.autoHide&&d.hide();d.addClass(a.fileClass);f.addClass(a.filenameClass);g.addClass(a.fileBtnClass);a.useID&&e.attr("id")!=""&&d.attr("id",a.idPrefix+"-"+e.attr("id"));
e.wrap(d);e.after(g);e.after(f);d=e.closest("div");f=e.siblings("."+a.filenameClass);g=e.siblings("."+a.fileBtnClass);if(!e.attr("size")){var j=d.width();e.attr("size",j/10)}var k=function(){var h=e.val();if(h==="")h=a.fileDefaultText;else{h=h.split(/[\/\\]+/);h=h[h.length-1]}f.text(h)};k();e.css("opacity",0).bind({"focus.uniform":function(){d.addClass(a.focusClass)},"blur.uniform":function(){d.removeClass(a.focusClass)},"mousedown.uniform":function(){c(b).is(":disabled")||d.addClass(a.activeClass)},
"mouseup.uniform":function(){d.removeClass(a.activeClass)},"mouseenter.uniform":function(){d.addClass(a.hoverClass)},"mouseleave.uniform":function(){d.removeClass(a.hoverClass);d.removeClass(a.activeClass)}});c.browser.msie?e.bind("click.uniform.ie7",function(){setTimeout(k,0)}):e.bind("change.uniform",k);e.attr("disabled")&&d.addClass(a.disabledClass);c.uniform.noSelect(f);c.uniform.noSelect(g);i(b)}function i(b){b=c(b).get();b.length>1?c.each(b,function(e,d){c.uniform.elements.push(d)}):c.uniform.elements.push(b)}
a=c.extend(c.uniform.options,a);var s=this;a.resetSelector!=false&&c(a.resetSelector).mouseup(function(){function b(){c.uniform.update(s)}setTimeout(b,10)});c.uniform.restore=function(b){if(b==undefined)b=c(c.uniform.elements);c(b).each(function(){if(c(this).is(":checkbox"))c(this).unwrap().unwrap();else if(c(this).is("select")){c(this).siblings("span").remove();c(this).unwrap()}else if(c(this).is(":radio"))c(this).unwrap().unwrap();else if(c(this).is(":file")){c(this).siblings("span").remove();c(this).unwrap()}else c(this).is("button, :submit, :reset, a, input[type='button']")&&
c(this).unwrap().unwrap();c(this).unbind(".uniform");c(this).css("opacity","1");var e=c.inArray(c(b),c.uniform.elements);c.uniform.elements.splice(e,1)})};c.uniform.noSelect=function(b){function e(){return false}c(b).each(function(){this.onselectstart=this.ondragstart=e;c(this).mousedown(e).css({MozUserSelect:"none"})})};c.uniform.update=function(b){if(b==undefined)b=c(c.uniform.elements);b=c(b);b.each(function(){var e=c(this);if(e.is("select")){var d=e.siblings("span"),f=e.parent("div");f.removeClass(a.hoverClass+
" "+a.focusClass+" "+a.activeClass);d.html(e.find(":selected").html());e.is(":disabled")?f.addClass(a.disabledClass):f.removeClass(a.disabledClass)}else if(e.is(":checkbox")){d=e.closest("span");f=e.closest("div");f.removeClass(a.hoverClass+" "+a.focusClass+" "+a.activeClass);d.removeClass(a.checkedClass);e.is(":checked")&&d.addClass(a.checkedClass);e.is(":disabled")?f.addClass(a.disabledClass):f.removeClass(a.disabledClass)}else if(e.is(":radio")){d=e.closest("span");f=e.closest("div");f.removeClass(a.hoverClass+
" "+a.focusClass+" "+a.activeClass);d.removeClass(a.checkedClass);e.is(":checked")&&d.addClass(a.checkedClass);e.is(":disabled")?f.addClass(a.disabledClass):f.removeClass(a.disabledClass)}else if(e.is(":file")){f=e.parent("div");d=e.siblings(a.filenameClass);btnTag=e.siblings(a.fileBtnClass);f.removeClass(a.hoverClass+" "+a.focusClass+" "+a.activeClass);d.text(e.val());e.is(":disabled")?f.addClass(a.disabledClass):f.removeClass(a.disabledClass)}else if(e.is(":submit")||e.is(":reset")||e.is("button")||
e.is("a")||b.is("input[type=button]")){f=e.closest("div");f.removeClass(a.hoverClass+" "+a.focusClass+" "+a.activeClass);e.is(":disabled")?f.addClass(a.disabledClass):f.removeClass(a.disabledClass)}})};return this.each(function(){if(c.support.selectOpacity){var b=c(this);if(b.is("select")){if(b.attr("multiple")!=true)if(b.attr("size")==undefined||b.attr("size")<=1)o(b)}else if(b.is(":checkbox"))p(b);else if(b.is(":radio"))q(b);else if(b.is(":file"))r(b);else if(b.is(":text, :password, input[type='email']"))l(b);
else if(b.is("textarea"))m(b);else if(b.is("a")||b.is(":submit")||b.is(":reset")||b.is("button")||b.is("input[type=button]"))n(b)}})}})(jQuery);
