jQuery.ui||function(b){function l(a,c,d,e){function f(h){h=b[a][c][h]||[];return typeof h=="string"?h.split(/,?\s+/):h}var g=f("getter");if(e.length==1&&typeof e[0]=="string")g=g.concat(f("getterSetter"));return b.inArray(d,g)!=-1}var m=b.fn.remove,n=b.browser.mozilla&&parseFloat(b.browser.version)<1.9;b.ui={version:"1.7.2",plugin:{add:function(a,c,d){a=b.ui[a].prototype;for(var e in d){a.plugins[e]=a.plugins[e]||[];a.plugins[e].push([c,d[e]])}},call:function(a,c,d){if((c=a.plugins[c])&&a.element[0].parentNode)for(var e=
0;e<c.length;e++)a.options[c[e][0]]&&c[e][1].apply(a.element,d)}},contains:function(a,c){return document.compareDocumentPosition?a.compareDocumentPosition(c)&16:a!==c&&a.contains(c)},hasScroll:function(a,c){if(b(a).css("overflow")=="hidden")return false;c=c&&c=="left"?"scrollLeft":"scrollTop";var d=false;if(a[c]>0)return true;a[c]=1;d=a[c]>0;a[c]=0;return d},isOverAxis:function(a,c,d){return a>c&&a<c+d},isOver:function(a,c,d,e,f,g){return b.ui.isOverAxis(a,d,f)&&b.ui.isOverAxis(c,e,g)},keyCode:{BACKSPACE:8,
CAPS_LOCK:20,COMMA:188,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38}};if(n){var k=b.attr,o=b.fn.removeAttr,j=/^aria-/,p=/^wairole:/;b.attr=function(a,c,d){var e=d!==undefined;return c=="role"?e?k.call(this,a,c,"wairole:"+d):(k.apply(this,arguments)||"").replace(p,""):j.test(c)?e?a.setAttributeNS("http://www.w3.org/2005/07/aaa",
c.replace(j,"aaa:"),d):k.call(this,a,c.replace(j,"aaa:")):k.apply(this,arguments)};b.fn.removeAttr=function(a){return j.test(a)?this.each(function(){this.removeAttributeNS("http://www.w3.org/2005/07/aaa",a.replace(j,""))}):o.call(this,a)}}b.fn.extend({remove:function(){b("*",this).add(this).each(function(){b(this).triggerHandler("remove")});return m.apply(this,arguments)},enableSelection:function(){return this.attr("unselectable","off").css("MozUserSelect","").unbind("selectstart.ui")},disableSelection:function(){return this.attr("unselectable",
"on").css("MozUserSelect","none").bind("selectstart.ui",function(){return false})},scrollParent:function(){var a;a=b.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(b.curCSS(this,"position",1))&&/(auto|scroll)/.test(b.curCSS(this,"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(b.curCSS(this,
"overflow",1)+b.curCSS(this,"overflow-y",1)+b.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!a.length?b(document):a}});b.extend(b.expr[":"],{data:function(a,c,d){return!!b.data(a,d[3])},focusable:function(a){var c=a.nodeName.toLowerCase(),d=b.attr(a,"tabindex");return(/input|select|textarea|button|object/.test(c)?!a.disabled:"a"==c||"area"==c?a.href||!isNaN(d):!isNaN(d))&&!b(a)["area"==c?"parents":"closest"](":hidden").length},tabbable:function(a){var c=b.attr(a,"tabindex");
return(isNaN(c)||c>=0)&&b(a).is(":focusable")}});b.widget=function(a,c){var d=a.split(".")[0];a=a.split(".")[1];b.fn[a]=function(e){var f=typeof e=="string",g=Array.prototype.slice.call(arguments,1);if(f&&e.substring(0,1)=="_")return this;if(f&&l(d,a,e,g)){var h=b.data(this[0],a);return h?h[e].apply(h,g):undefined}return this.each(function(){var i=b.data(this,a);!i&&!f&&b.data(this,a,new b[d][a](this,e))._init();i&&f&&b.isFunction(i[e])&&i[e].apply(i,g)})};b[d]=b[d]||{};b[d][a]=function(e,f){var g=
this;this.namespace=d;this.widgetName=a;this.widgetEventPrefix=b[d][a].eventPrefix||a;this.widgetBaseClass=d+"-"+a;this.options=b.extend({},b.widget.defaults,b[d][a].defaults,b.metadata&&b.metadata.get(e)[a],f);this.element=b(e).bind("setData."+a,function(h,i,q){if(h.target==e)return g._setData(i,q)}).bind("getData."+a,function(h,i){if(h.target==e)return g._getData(i)}).bind("remove",function(){return g.destroy()})};b[d][a].prototype=b.extend({},b.widget.prototype,c);b[d][a].getterSetter="option"};
b.widget.prototype={_init:function(){},destroy:function(){this.element.removeData(this.widgetName).removeClass(this.widgetBaseClass+"-disabled "+this.namespace+"-state-disabled").removeAttr("aria-disabled")},option:function(a,c){var d=a,e=this;if(typeof a=="string"){if(c===undefined)return this._getData(a);d={};d[a]=c}b.each(d,function(f,g){e._setData(f,g)})},_getData:function(a){return this.options[a]},_setData:function(a,c){this.options[a]=c;if(a=="disabled")this.element[c?"addClass":"removeClass"](this.widgetBaseClass+
"-disabled "+this.namespace+"-state-disabled").attr("aria-disabled",c)},enable:function(){this._setData("disabled",false)},disable:function(){this._setData("disabled",true)},_trigger:function(a,c,d){var e=this.options[a];a=a==this.widgetEventPrefix?a:this.widgetEventPrefix+a;c=b.Event(c);c.type=a;if(c.originalEvent){a=b.event.props.length;for(var f;a;){f=b.event.props[--a];c[f]=c.originalEvent[f]}}this.element.trigger(c,d);return!(b.isFunction(e)&&e.call(this.element[0],c,d)===false||c.isDefaultPrevented())}};
b.widget.defaults={disabled:false};b.ui.mouse={_mouseInit:function(){var a=this;this.element.bind("mousedown."+this.widgetName,function(c){return a._mouseDown(c)}).bind("click."+this.widgetName,function(c){if(a._preventClickEvent){a._preventClickEvent=false;c.stopImmediatePropagation();return false}});if(b.browser.msie){this._mouseUnselectable=this.element.attr("unselectable");this.element.attr("unselectable","on")}this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName);
b.browser.msie&&this.element.attr("unselectable",this._mouseUnselectable)},_mouseDown:function(a){a.originalEvent=a.originalEvent||{};if(!a.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(a);this._mouseDownEvent=a;var c=this,d=a.which==1,e=typeof this.options.cancel=="string"?b(a.target).parents().add(a.target).filter(this.options.cancel).length:false;if(!d||e||!this._mouseCapture(a))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){c.mouseDelayMet=
true},this.options.delay);if(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)){this._mouseStarted=this._mouseStart(a)!==false;if(!this._mouseStarted){a.preventDefault();return true}}this._mouseMoveDelegate=function(f){return c._mouseMove(f)};this._mouseUpDelegate=function(f){return c._mouseUp(f)};b(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);b.browser.safari||a.preventDefault();return a.originalEvent.mouseHandled=true}},
_mouseMove:function(a){if(b.browser.msie&&!a.button)return this._mouseUp(a);if(this._mouseStarted){this._mouseDrag(a);return a.preventDefault()}if(this._mouseDistanceMet(a)&&this._mouseDelayMet(a))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,a)!==false)?this._mouseDrag(a):this._mouseUp(a);return!this._mouseStarted},_mouseUp:function(a){b(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=
false;this._preventClickEvent=a.target==this._mouseDownEvent.target;this._mouseStop(a)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}};b.ui.mouse.defaults={cancel:null,distance:1,delay:0}}(jQuery);
