(function(q){function A(d){return O.call(d)===ua}function P(d,e){var h=/^\w+\:\/\//;if(typeof d!=r)d="";if(typeof e!=r)e="";d=(/^\/\//.test(d)?$.protocol:"")+d;d=(h.test(d)?"":e)+d;return(h.test(d)?"":d.charAt(0)==="/"?aa:ba)+d}function va(d){return P(d).indexOf(aa)===0}function wa(d){for(var e,h=-1;e=xa[++h];)if(typeof e.src==r&&d===P(e.src)&&e.type!==ca)return i;return j}function G(d,e){function h(a,b){if(a[w]&&a[w]!==da&&a[w]!=="loaded"||b[B])return j;a[ea]=a[H]=f;return i}function o(a,b,c){if((c=
!!c)||h(a,b)){b[B]=i;for(var g in l)if(l[Q](g)&&!l[g][B])return;fa=i;ga()}}function s(a){if(A(a[C])){a[C]();a[C]=f}}function ya(a,b){if(h(a,b)){b[m]=i;D(function(){t[b[E]].removeChild(a);s(b)},0)}}function za(a,b){if(a[w]===4){a[H]=I;b[m]=i;D(function(){s(b)},0)}}function R(a,b,c,g,k,u){var x=a[E];D(function(){if("item"in t[x]){if(!t[x][0]){D(arguments.callee,25);return}t[x]=t[x][0]}var p=n.createElement(S);if(typeof c==r)p.type=c;if(typeof g==r)p.charset=g;if(A(k)){p[ea]=p[H]=function(){k(p,a)};
p.src=b;if(ha)p.async=j}t[x].insertBefore(p,x===z?t[x].firstChild:f);if(typeof u==r){p.text=u;o(p,a,i)}},0)}function ia(a,b,c,g){T[a[U]]=i;R(a,b,c,g,o)}function ja(a,b,c,g){var k=arguments;if(v&&a[m]==f){a[m]=j;R(a,b,ca,g,ya)}else if(!v&&a[m]!=f&&!a[m])a[C]=function(){ja.apply(f,k)};else v||ia.apply(f,k)}function ka(a,b,c,g){var k=arguments,u;if(v&&a[m]==f){a[m]=j;u=a.xhr=la?new la("Microsoft.XMLHTTP"):new q.XMLHttpRequest;u[H]=function(){za(u,a)};u.open("GET",b);u.send("")}else if(!v&&a[m]!=f&&!a[m])a[C]=
function(){ka.apply(f,k)};else if(!v){T[a[U]]=i;R(a,b,c,g,f,a.xhr.responseText);a.xhr=f}}function ma(a){if(!(typeof a=="undefined"||!a)){if(a.allowDup==f)a.allowDup=e.dupe;var b=a.type,c=a.charset,g=a.allowDup;a=P(a.src,Aa);var k=va(a);if(typeof c!=r)c=f;g=!!g;if(!g&&(T[a]!=f||v&&l[a]||wa(a)))l[a]!=f&&l[a][m]&&!l[a][B]&&k&&o(f,l[a],i);else{if(l[a]==f)l[a]={};g=l[a];if(g[E]==f)g[E]=Ba;g[B]=j;g[U]=a;J=i;if(!K&&na&&k)ka(g,a,b,c);else!K&&oa?ja(g,a,b,c):ia(g,a,b,c)}}}function V(a){d&&!K&&L.push(a);if(!d||
F)a()}function pa(a){var b=[],c;for(c=-1;++c<a.length;)if(O.call(a[c])===Ca)b=b.concat(pa(a[c]));else b[b.length]=a[c];return b}d=!!d;if(e==f)e=y;var fa=j,F=d&&e[M],oa=F&&e.cache,K=F&&e.order,na=F&&e.xhr,Da=e[W],Ba=e.which,Aa=e.base,ga=I,J=j,N,v=i,l={},L=[],X=f;F=oa||na||K;N={script:function(){qa(X);var a=pa(arguments),b=N,c;if(Da)for(c=-1;++c<a.length;){if(A(a[c]))a[c]=a[c]();if(c===0)V(function(){ma(typeof a[0]==r?{src:a[0]}:a[0])});else b=b.script(a[c]);b=b.wait()}else{for(c=-1;++c<a.length;)if(A(a[c]))a[c]=
a[c]();V(function(){for(c=-1;++c<a.length;)ma(typeof a[c]==r?{src:a[c]}:a[c])})}X=D(function(){v=j},5);return b},wait:function(a){qa(X);v=j;A(a)||(a=I);var b=G(d||J,e),c=b.trigger,g=function(){try{a()}catch(u){}c()};delete b.trigger;var k=function(){if(J&&!fa)ga=g;else g()};d&&!J?L.push(k):V(k);return b}};N.trigger=d?function(){for(var a,b=-1;a=L[++b];)a();L=[]}:I;return N}function ra(d){var e,h={},o={UseCachePreload:"cache",UseLocalXHR:"xhr",UsePreloading:M,AlwaysPreserveOrder:W,AllowDuplicates:"dupe"},
s={AppendTo:E,BasePath:"base"};for(e in o)s[e]=o[e];h.order=!!y.order;for(e in s)if(s[Q](e)&&y[s[e]]!=f)h[s[e]]=d[e]!=f?d[e]:y[s[e]];for(e in o)if(o[Q](e))h[o[e]]=!!h[o[e]];if(!h[M])h.cache=h.order=h.xhr=j;h.which=h.which===z||h.which===Y?h.which:z;return h}var r="string",z="head",Y="body",S="script",w="readyState",m="preloaddone",C="loadtrigger",U="srcuri",M="preload",da="complete",B="done",E="which",W="preserve",H="onreadystatechange",ea="onload",Q="hasOwnProperty",ca="script/cache",ua="[object Function]",
Ca="[object Array]",f=null,i=true,j=false,n=q.document,$=q.location,la=q.ActiveXObject,D=q.setTimeout,qa=q.clearTimeout,Z=function(d){return n.getElementsByTagName(d)},O=Object.prototype.toString,I=function(){},t={},T={},ba=/^[^?#]*\//.exec($.href)[0],aa=/^\w+\:\/\/\/?[^\/]+/.exec(ba)[0],xa=Z(S),sa=q.opera&&O.call(q.opera)=="[object Opera]",ta="MozAppearance"in n.documentElement.style,ha=n.createElement(S).async===true,y={cache:!(ta||sa),order:ta||sa||ha,xhr:i,dupe:i,base:"",which:z};y[W]=j;y[M]=
i;t[z]=n.head||Z(z);t[Y]=Z(Y);q.$LAB={setGlobalDefaults:function(d){y=ra(d)},setOptions:function(d){return G(j,ra(d))},script:function(){return G().script.apply(f,arguments)},wait:function(){return G().wait.apply(f,arguments)}};(function(d,e,h){if(n[w]==f&&n[d]){n[w]="loading";n[d](e,h=function(){n.removeEventListener(e,h,j);n[w]=da},j)}})("addEventListener","DOMContentLoaded")})(window);
