(function(){var e=window.melange;this.prototype=new e.templates._baseTemplate;this.prototype.constructor=e.templates._baseTemplate;e.templates._baseTemplate.apply(this,arguments);var j=this,A={".model_select_option":{"model<-models":{".":"model.name",".@value":"model.name"}}},n={".@id":"model.name",".model_name":"model.name",".property_set_container":{"property_set<-properties_data":{".@property_set_name":"property_set.name",".property_set_name":"property_set.name",".property_container":{"property<-property_set.properties":{".@property_name":"property.name",
".@reference_class":"property.reference_class",".property_name":function(a){context=a.context;property=a.item;a="";if(property.required)a="(*) ";var b="";if(property.reference_class)b=" -> "+property.reference_class;return a+property.verbose_name+" - "+property.type+b},".provider_select@property_name":"property.name",".provider_select@required":"property.required",".provider_select_option":{"provider<-property.providers":{".":"provider.name",".@value":"provider.name"}}}}}}};jQuery.extend(n,{".@class":function(){return"model_container"}});
var B={".@provider_name":"provider.name",".provider_description":"provider.description",".provider_parameter_container":{"parameter<-provider.parameters":{".@parameter_name":"parameter.name",".parameter_name":"parameter.verbose_name",".parameter_description":"parameter.description",".parameter_required":function(a){parameter=a.item;if(parameter.required)return"(required)";return""},".provider_parameter_input@parameter_name":"parameter.name"}}},C={".model_select_option":{"model<-models":{".":function(a){model=
a.item;prefix="";for(i=0;i<model.level-1;++i)prefix+="| ";if(model.level>0)prefix+="+-";return prefix+model.name},".@value":"model.name"}}},v=function(a,b){var c=a.target;a=jQuery(jQuery(c).parents(".property_container")[0]);a=jQuery(".reference_model_parameters",a);var d=c.value;e.seeder.log(5,"Adding new model reference provider to "+d);c=e.seeder.getModel(d);d=e.seeder.getProperties(d);b=b({model:c,properties_data:d});jQuery(a).html(b);jQuery(".model_remove_link").click(s);jQuery(".provider_select").change(t);
o(a);u(a)},D=function(a){v(a,j.nestedModelContainerRenderer)},E=function(a){v(a,j.modelContainerRenderer)},w=function(a,b,c){a=a.attr("reference_class");a={models:e.seeder.getModelChildren(a)};a=j.referenceModelSelectorRenderer(a);b.html(a);jQuery(".model_select",b).change(c);jQuery(".model_select",b).change()},F=function(a){a=jQuery(a.target).parents(".provider_container")[0];var b=jQuery(a).attr("provider_name"),c=jQuery(".test_provider_response",a),d={};jQuery(".provider_parameter_input",a).each(function(f,
h){f=jQuery(h).attr("parameter_name");h=h.value;if(h!=="")d[f]=h});var g={provider_name:b,parameters:d};json=JSON.stringify(g);jQuery.post("/seeder/test_provider",{xsrf_token:window.xsrf_token,data:json},function(f){g=JSON.parse(f);jQuery(c).text(g.value)})},G=function(a){var b=jQuery(".provider_parameters",a),c=a.attr("property_name");a=a.parents(".property_set_container")[0];a=jQuery(a).attr("property_set_name");a=e.seeder.getModel(a);var d=null;jQuery.each(a.properties,function(g,f){if(f.name===
c)d=f});if(d&&d.choices){b=jQuery("input[parameter_name=choices]",b)[0];d.choices.join(",");b.value=d.choices.join(",")}},H=function(a){var b=jQuery(".provider_parameters",a),c=a.attr("property_name");a=a.parents(".property_set_container")[0];a=jQuery(a).attr("property_set_name");a=e.seeder.getModel(a);var d=null;jQuery.each(a.properties,function(g,f){if(f.name===c)d=f});if(d&&d.reference_class)jQuery("input[parameter_name=model_name]",b)[0].value=d.reference_class},x=function(a){var b=jQuery(jQuery(a).parents(".property_container")[0]);
a=a.value;var c=jQuery(".provider_parameters",b);c.empty();if(a!=="none")if(a==="NewModel")w(b,c,D);else if(a==="RelatedModels")w(b,c,E);else{e.seeder.log(5,"Adding parameters for "+a+"...");e.seeder.getProvidersList();data={provider:e.seeder.getProvider(a)};html=j.providerContainerRenderer(data);e.seeder.log(5,"Parameters added!");c.html(html);jQuery(".test_provider").click(F);a==="RandomWordProvider"&&G(b);a==="RandomReferenceProvider"&&H(b)}},t=function(a){a=a.target;e.seeder.log(5,"Provider changed!");
x(a)},s=function(a){a=jQuery(a.target).parent().parent();jQuery(a).remove()},I=function(a){var b=e.seeder.getModel(a),c=e.seeder.getProperties(a);data={model:b,properties_data:c};b=jQuery(j.modelContainerRenderer(data));jQuery(".provider_select",b).change(t);jQuery(".model_remove_link",b).click(s);e.seeder.log(5,"Model "+a+" added!");o(b);u(b);return b},y=function(a){a=I(a);jQuery("#selected_models").append(a);return a},u=function(a){e.seeder.log(5,"Adding default providers!!!");jQuery(".provider_select",
a).each(function(b,c){if(c.value==="none"&&jQuery(c).attr("required")==="true")for(i=0;i<c.options.length;++i){b=c.options[i];if(b.value.match("^Random")=="Random"){c.value=b.value;jQuery(c).change();break}}})},J=function(){var a=jQuery(".model_select")[0].value;e.seeder.log(5,"Adding model "+a+"...");y(a)},p=function(a){var b={name:a.id},c=jQuery("input#number",a)[0];if(c)b.number=c.value;var d={};jQuery(".property_container",a).each(function(g,f){g=jQuery(f).attr("property_name");var h=jQuery(".provider_select",
f)[0].value,k=jQuery(a).attr("class");if(jQuery(f).parents("."+k)[0]===a)if(h!=="none"){k={};k.provider_name=h;var l={};if(h==="NewModel"){f=jQuery(".model_container",f)[0];l=p(f,true)}else if(h==="RelatedModels"){f=jQuery(".model_container",f)[0];l=p(f,true)}else jQuery(".provider_parameter_container",f).each(function(z,m){z=jQuery(m).attr("parameter_name");if(m=jQuery("input",m)[0].value)l[z]=m});k.parameters=l;d[g]=k}});b.properties=d;return b},q=function(){e.seeder.log(5,"Building configuration sheet...");
var a=[];jQuery(".model_container").each(function(b,c){b=jQuery(c).parent()[0];jQuery(b).attr("id")==="selected_models"&&a.push(p(c))});e.seeder.log(5,"Configuration sheet built:");e.seeder.log(5,a);return a},K=function(){e.seeder.log(5,"Validating configuration sheet");var a=q();a=JSON.stringify(a);jQuery.post("/seeder/validate_configuration_sheet",{xsrf_token:window.xsrf_token,data:a},function(b){data=JSON.parse(b)})},L=function(){var a=q();a=JSON.stringify(a);jQuery("#download_configuration_sheet_data").attr("value",
a)},M=function(a){e.seeder.log(5,"Response:");e.seeder.log(5,a);data=JSON.parse(a);if(data.response==="success")window.location="/mapreduce/detail?mapreduce_id="+data.id;else e.seeder.log(5,"ERROR!!!")},N=function(){var a=q();e.seeder.sendConfigurationSheet(a,M)},r=function(a,b){jQuery.each(a.properties,function(c,d){var g=jQuery(".property_container[property_name="+c+"]",b).filter(function(){return jQuery(this).parents(".model_container")[0]===b[0]})[0];c=jQuery(".provider_select",g)[0];c.value=
d.provider_name;x(c);c=d.parameters;if(d.provider_name==="NewModel"){d=jQuery(".model_select",g);d.attr("value",c.name);d.change();d=jQuery(".model_container",g);r(c,d)}else if(d.provider_name==="RelatedModels"){d=jQuery(".model_select",g);d.attr("value",c.name);d.change();d=jQuery(".model_container",g);jQuery("input#number",d)[0].value=c.number;r(c,d)}else jQuery.each(c,function(f,h){jQuery(".provider_parameter_input[parameter_name="+f+"]",g)[0].value=h})})},O=function(a){e.seeder.log(5,"Loading configuration sheet.");
a=JSON.parse(a);jQuery.each(a,function(b,c){b=y(c.name);jQuery("input#number",b)[0].value=c.number;r(c,b)})},o=function(a){jQuery(".toggle_container",a).hide();jQuery(".trigger",a).click(function(){jQuery(this).toggleClass("active").next().slideToggle("fast")})},P=function(){jQuery("#add_model_button").click(J);jQuery("#validate_configuration_sheet_button").click(K);jQuery("#download_configuration_sheet_button").click(L);jQuery("#send_configuration_sheet_button").click(N);jQuery("#add_model_button").hide();
jQuery("#validate_configuration_sheet_button").hide();jQuery("#send_configuration_sheet_button").hide();jQuery("#download_configuration").hide();jQuery("#load_configuration").hide();j.modelSelectorRenderer=$p("#models_selector").compile(A);jQuery("#models_selector").empty();jQuery("#models_selector").text("Loading, please wait...");j.modelContainerRenderer=$p(".model_container").compile(n);jQuery(".model_container").remove();j.nestedModelContainerRenderer=$p(".nested_model_container").compile(n);
jQuery(".nested_model_container").remove();j.providerContainerRenderer=$p(".provider_container").compile(B);jQuery(".provider_container").remove();j.referenceModelSelectorRenderer=$p(".reference_model_selector").compile(C);jQuery(".reference_model_selector").remove();o()},Q=function(){data={models:e.seeder.getModels()};jQuery("#models_selector").html(j.modelSelectorRenderer(data));jQuery("#add_model_button").show();jQuery("#validate_configuration_sheet_button").show();jQuery("#send_configuration_sheet_button").show();
jQuery("#download_configuration").show();jQuery("#load_configuration").show();e.seeder.log(5,"Model list populated!")},R=function(){e.seeder.log(5,"Got data!");Q(e.seeder.getModels());configuration_sheet=this.context.configuration_sheet;configuration_sheet!==""&&O(configuration_sheet)};jQuery(document).ready(function(){e.logging.setDebug();P();e.seeder.getData(R)})})();
