(function(){function D(g,h,p,o){var b=this,y={datatype:E,viewrecords:true},t={edit:false,add:false,del:false,afterRefresh:function(){b.refreshData();b.jqgrid.object.trigger("reloadGrid")}};g=g;h=h;this.configuration=p;this.operations=o;this.jqgrid={id:null,object:null,options:null,last_selected_row:null,editable_columns:[],dirty_fields:{},pager:{id:null,options:null}};this.data={data:[],all_data:[],filtered_data:null};var v={enableDisableButtons:function(a){return function(d){function c(k){var i=
jQuery("#"+a.jqgrid.id).jqGrid("getRowData",k),e=s.from(a.data.all_data).equals("columns.key",i.key).select()[0];if(a.jqgrid.dirty_fields[i.key]===undefined)a.jqgrid.dirty_fields[i.key]=[];var j=[],u=[];jQuery.each(i,function(n,r){r!=e.columns[n]?j.push(n):u.push(n)});jQuery.each(j,function(n,r){jQuery.inArray(r,a.jqgrid.dirty_fields[i.key])===-1&&a.jqgrid.dirty_fields[i.key].push(r)});jQuery.each(u,function(n,r){n=jQuery.inArray(r,a.jqgrid.dirty_fields[i.key]);n!==-1&&a.jqgrid.dirty_fields[i.key].splice(n,
1)});a.jqgrid.dirty_fields[i.key].length===0&&delete a.jqgrid.dirty_fields[i.key];jQuery.each(a.operations.buttons,function(n,r){if(r.type==="post_edit"){n=jQuery("#"+a.jqgrid.id+"_buttonOp_"+r.id);C(a.jqgrid.dirty_fields)?n.attr("disabled","disabled"):n.removeAttr("disabled")}})}var l=a.jqgrid.object.jqGrid("getGridParam","multiselect")?"selarrrow":"selrow",f=a.jqgrid.object.jqGrid("getGridParam",l);if(!f instanceof Array)f=[f];if(f.length===1)if(d&&d!==a.jqgrid.last_selected_row){jQuery("#"+a.jqgrid.id).restoreRow(a.jqgrid.last_selected_row);
jQuery("#"+a.jqgrid.id).jqGrid("editRow",d,true,null,null,"clientArray",null,c);a.jqgrid.last_selected_row=d}jQuery.each(a.operations.buttons,function(k,i){k=jQuery("#"+a.jqgrid.id+"_buttonOp_"+i.id);if(i.type!=="post_edit")if(f.length>=i.real_bounds[0]&&f.length<=i.real_bounds[1]){k.removeAttr("disabled");if(i.real_bounds[0]===1&&i.real_bounds[1]===1&&k.data("melange")!==undefined){var e=a.jqgrid.object.jqGrid("getRowData",f[0]);e=s.from(a.data.all_data).equals("columns.key",e.key).select()[0];var j=
k.data("melange").click;k.click(j(e.operations.buttons[i.id].link));k.attr("value",e.operations.buttons[i.id].caption)}}else k.attr("disabled","disabled")})}}(b),global_button_functions:{redirect_simple:function(a){return a.new_window?function(){window.open(a.link)}:function(){window.location.href=a.link}},redirect_custom:function(a){return function(d){return a.new_window?function(){window.open(d)}:function(){window.location.href=d}}},post:function(a){return function(){var d=m.get(a.idx).jqgrid.object.jqGrid("getGridParam",
"multiselect")?"selarrrow":"selrow";d=m.get(a.idx).jqgrid.object.jqGrid("getGridParam",d);d instanceof Array||(d=d===null?[]:[d]);var c=[];if(!(d.length<a.real_bounds[0]||d.length>a.real_bounds[1])){jQuery.each(d,function(l,f){var k=jQuery("#"+m.get(a.idx).jqgrid.id).jqGrid("getRowData",f);s.from(m.get(a.idx).all_data).equals("columns.key",k.key).select();var i={};jQuery.each(a.keys,function(e,j){e=k[j];if(jQuery(e).hasClass("listsnoul"))e=/^<a\b[^>]*>(.*?)<\/a>$/.exec(e)[1];i[j]=e});c.push(i)});
if(a.url==="")a.url=window.location.href;jQuery.post(a.url,{xsrf_token:window.xsrf_token,idx:a.idx,button_id:a.button_id,data:JSON.stringify(c)},function(l){if(a.redirect=="true")try{var f=JSON.parse(l);if(f.data.url!==undefined)window.location.href=f.data.url}catch(k){}l=parseInt(a.refresh,10);if(!isNaN(l)){m.get(l).refreshData();jQuery("#"+m.get(l).jqgrid.id).trigger("reloadGrid")}if(a.refresh=="current"){m.get(a.idx).refreshData();jQuery("#"+m.get(a.idx).jqgrid.id).trigger("reloadGrid")}else if(a.refresh==
"all"){l=m.getAll();jQuery.each(l,function(i,e){e.refreshData();jQuery("#"+m.get(i).jqgrid.id).trigger("reloadGrid")})}})}}},post_edit:function(a){return function(){var d=m.get(a.idx).jqgrid,c={};if(!(d.editable_columns.length===0&&C(d.dirty_fields))){for(var l=d.object.jqGrid("getGridParam","records"),f=1;f<=l;f++){var k=jQuery("#"+d.id).jqGrid("getRowData",f);if(d.dirty_fields[k.key]!==undefined){c[k.key]={};jQuery.each(d.dirty_fields[k.key],function(i,e){c[k.key][e]=k[e]})}}if(a.url==="")a.url=
window.location.href;jQuery.post(a.url,{xsrf_token:window.xsrf_token,idx:a.idx,button_id:a.button_id,data:JSON.stringify(c)},function(i){if(a.redirect=="true")try{var e=JSON.parse(i);if(e.data.url!==undefined)window.location.href=e.data.url}catch(j){}i=parseInt(a.refresh,10);if(!isNaN(i)){m.get(i).refreshData();jQuery("#"+m.get(i).jqgrid.id).trigger("reloadGrid")}if(a.refresh=="current"){m.get(a.idx).refreshData();jQuery("#"+m.get(a.idx).jqgrid.id).trigger("reloadGrid")}else if(a.refresh=="all"){i=
m.getAll();jQuery.each(i,function(u,n){n.refreshData();jQuery("#"+m.get(u).jqgrid.id).trigger("reloadGrid")})}})}}}},row_functions:{redirect_custom:function(a){return function(d,c){return a.new_window||c.which===2||c.which===1&&c.ctrlKey?function(){window.open(d)}:function(){window.location.href=d}}}}},B=function(){jQuery("#"+g).replaceWith(['<p id="temporary_list_placeholder_',h,'"></p>','<table id="'+b.jqgrid.id+'"',' cellpadding="0" cellspacing="0"></table>','<div id="'+b.jqgrid.pager.id+'"',' style="text-align:center"></div>'].join(""))},
z=function(){var a="",d=0,c=function(){var l="?";if(window.location.href.indexOf("?")!==-1)l="&";jQuery.ajax({async:true,cache:false,url:[window.location.href,l,"fmt=json&limit=150",a===""?"":"&start="+a,"&idx=",h].join(""),timeout:6E4,tryCount:1,retryLimit:5,error:function(f){if(f.status==500){this.tryCount++;if(this.tryCount<=this.retryLimit)jQuery.ajax(this);else{jQuery("#temporary_list_placeholder_"+h).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');
jQuery("#load_"+b.jqgrid.id).hide()}}else{jQuery("#temporary_list_placeholder_"+h).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');jQuery("#load_"+b.jqgrid.id).hide()}},success:function(f){var k=d>0,i=!f.data[a].length;if(f.data[a]!==undefined&&(!k||!i)){if(b.configuration===null)b.configuration=f.configuration;if(b.operations===null)b.operations=f.operations;k=f.data[a];jQuery.each(k,function(){b.data.data.push(this.columns);b.data.all_data.push(this)});
b.jqgrid.object===null?w():b.jqgrid.object.trigger("reloadGrid");if(k[k.length-1]!==undefined){a=f.next;setTimeout(c,100);d++}else{jQuery("#temporary_list_placeholder_"+h).remove();jQuery("#load_"+b.jqgrid.id).hide()}}else{jQuery("#temporary_list_placeholder_"+h).remove();jQuery("#load_"+b.jqgrid.id).hide();jQuery("#"+b.jqgrid.id)[0].triggerToolbar();jQuery.each(b.configuration.colModel,function(e,j){j.editable!==undefined&&j.editable===true&&b.jqgrid.editable_columns.push(j.name)});jQuery("#t_"+
b.jqgrid.id).children().remove();b.operations!==undefined&&b.operations.buttons!==undefined&&jQuery.each(b.operations.buttons,function(e,j){e=b.jqgrid.id+"_buttonOp_"+j.id;jQuery("#t_"+b.jqgrid.id).append("<input type='button' value='"+j.caption+"' style='float:left' id='"+e+"'/>");j.parameters.idx=h;if(j.type!=="post_edit"){j.real_bounds=j.bounds;var u=j.real_bounds.indexOf("all");if(u!==-1)j.real_bounds[u]=b.jqgrid.object.jqGrid("getGridParam","records");j.parameters.real_bounds=j.real_bounds}if(j.type===
"post_edit"||j.real_bounds[0]>0)jQuery("#"+e).attr("disabled","disabled");j.parameters.button_id=j.id;jQuery("#"+e).click(v.global_button_functions[j.type](j.parameters));j.type=="redirect_custom"&&jQuery("#"+e).data("melange",{click:v.global_button_functions[j.type](j.parameters)})});jQuery("#t_"+b.jqgrid.id).css("padding-bottom","3px");jQuery("#t_"+b.jqgrid.id).append("<input type='button' value='CSV Export' style='float:right; padding-bottom:1px' id='csvexport_"+b.jqgrid.id+"'/>");jQuery("#csvexport_"+
b.jqgrid.id).button();jQuery("#csvexport_"+b.jqgrid.id).click(function(){var e=[];e[0]=[];if(b.data.data[0]!==undefined||b.data.filtered_data[0]!==undefined){var j=b.data.filtered_data||b.data.data;jQuery.each(b.configuration.colNames,function(n,r){n=r;n=n.replace(/\"|&quot;|&#34;/g,'""');if(n.indexOf(",")!==-1||n.indexOf('"')!==-1||n.indexOf("\r\n")!==-1)n='"'+n+'"';e[0].push(n)});e[0]=e[0].join(",");var u=[];jQuery.each(b.configuration.colModel,function(n,r){u.push(r.name)});jQuery.each(j,function(n,
r){e[e.length]=[];jQuery.each(u,function(q,A){q=r[A];if(q===null)q="";if(q===undefined)q="";q=q.toString();A=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(q);if(A!==null)q=A[1];q=q.replace(/\"|&quot;|&#34;/g,'""');if(q.indexOf(",")!==-1||q.indexOf('"')!==-1||q.indexOf("\r\n")!==-1)q='"'+q+'"';e[e.length-1].push(q)});e[e.length-1]=e[e.length-1].join(",")});e=e.join("\r\n");jQuery("#csv_dialog").remove();jQuery("body").append(["<div id='csv_dialog' style='display:none'>  <h3>Now you can copy and paste CSV data from the text area to a new file:</h3>  <textarea style='width:450px;height:250px'>",
e,"</textarea></div>"].join(""));jQuery("#csv_dialog").dialog({height:420,width:500,modal:true,buttons:{Close:function(){jQuery(this).dialog("close")}}})}});jQuery("#t_"+b.jqgrid.id).append("<div style='float:right;margin-right:4px;'><input type='checkbox' id='regexp_"+b.jqgrid.id+"'/>RegExp Search</div>");jQuery("#regexp_"+b.jqgrid.id).click(function(){jQuery("#"+b.jqgrid.id).jqGrid().trigger("reloadGrid")});f=jQuery.Event("melange_list_loaded");f.list_object=b;b.jqgrid.object.trigger(f)}}})};setTimeout(c,
100)};this.refreshData=function(){b.data={data:[],all_data:[],filtered_data:null};z()};var w=function(){var a=jQuery.extend(b.configuration,{postData:{my_index:h},onSelectAll:v.enableDisableButtons,onSelectRow:v.enableDisableButtons}),d={caption:"",buttonicon:"ui-icon-calculator",onClickButton:function(){jQuery("#"+b.jqgrid.id).setColumns({colnameview:false,jqModal:true,ShrinkToFit:true});return false},position:"last",title:"Show/Hide Columns",cursor:"pointer"};jQuery("#"+b.jqgrid.id).jqGrid(jQuery.extend(b.jqgrid.options,
a)).jqGrid("navGrid","#"+b.jqgrid.pager.id,b.jqgrid.pager.options,{},{},{},{closeAfterSearch:true,multipleSearch:true},{}).jqGrid("navButtonAdd","#"+b.jqgrid.pager.id,d);jQuery("#"+b.jqgrid.id).jqGrid("filterToolbar",{});jQuery("#load_"+b.jqgrid.id).closest("div").css("line-height","100%");jQuery("#load_"+b.jqgrid.id).html("<img src='/soc/content/images/jqgrid_loading.gif'></img>");jQuery("#load_"+b.jqgrid.id).show();b.jqgrid.object=jQuery("#"+b.jqgrid.id)};this.getDiv=function(){return g};this.getIdx=
function(){return h};(function(){jQuery(function(){if(jQuery("#"+g).length===0)throw new x.error.divNotExistent("Div "+g+" is not existent");b.jqgrid.id="jqgrid_"+g;b.jqgrid.pager.id="jqgrid_pager_"+g;b.jqgrid.options=jQuery.extend(y,{pager:"#"+b.jqgrid.pager.id});b.jqgrid.pager.options=t;m.add(b);B();w();z()})})()}if(window.melange===undefined)throw new Error("Melange not loaded");var x=window.melange;if(window.jLinq===undefined)throw new Error("jLinq not loaded");var s=window.jLinq;x.list=window.melange.list=
function(){return new x.list};var F=x.logging.debugDecorator(x.list);x.error.createErrors(["listIndexNotValid","divNotExistent","indexAlreadyExistent"]);var C=function(g){for(var h in g)return false;return true},E=function(g){var h=g.my_index,p=m.get(h).data.data,o=p,b="",y={eq:{method:"equals",not:false},ne:{method:"equals",not:true},lt:{method:"less",not:false},le:{method:"lessEquals",not:false},gt:{method:"greater",not:false},ge:{method:"greaterEquals",not:false},bw:{method:"startsWith",not:false},
bn:{method:"startsWith",not:true},ew:{method:"endsWith",not:false},en:{method:"endsWith",not:true},cn:{method:"contains",not:false},nc:{method:"contains",not:true},"in":{method:"match",not:false},ni:{method:"match",not:true}};if(g._search&&g.filters){var t=JSON.parse(g.filters);if(t.rules[0].data!==""){b=t.groupOp;if(b==="OR")o={};jQuery.each(t.rules,function(d,c){if(c.op==="in"||c.op==="ni")c.data=c.data.split(",").join("|");o=y[c.op].not?b==="OR"?s.from(o).union(s.from(p).not()[y[c.op].method](c.field,
c.data).select()).select():s.from(o).not()[y[c.op].method](c.field,c.data).select():b==="OR"?s.from(o).union(s.from(p)[y[c.op].method](c.field,c.data).select()).select():s.from(o)[y[c.op].method](c.field,c.data).select()})}}else p[0]!==undefined&&jQuery.each(p[0],function(d){if(g[d]!==undefined){var c=jQuery("#regexp_"+m.get(h).jqgrid.id).is(":checked"),l=false;jQuery.each(m.get(h).configuration.colModel,function(f,k){if(k.editoptions!==undefined&&d===k.name)l=true});o=c||l?s.from(o).match(d,g[d]).select():
s.from(o).contains(d,g[d]).select()}});var v=g.sidx;t=g.sord;jQuery.each(m.get(h).configuration.colModel,function(d,c){if(c.name===v&&(c.sorttype==="integer"||c.sorttype==="int"))jQuery.each(o,function(l,f){l=parseInt(f[v],10);isNaN(l)||(f[v]=l)})});t=t==="asc"?"":"-";if(o.length>0)o=s.from(o).ignoreCase().orderBy(t+v).select();m.get(h).data.filtered_data=o;if(g.rows===-1)g.rows=m.get(h).data.filtered_data.length;t=(g.page-1)*g.rows;for(var B=g.page*g.rows-1,z={page:g.page,total:o.length===0?0:Math.ceil(o.length/
g.rows),records:o.length,rows:[]},w=t;w<=B;w++)if(o[w]!==undefined){var a=[];p[0]!==undefined&&jQuery.each(m.get(h).configuration.colModel,function(d,c){var l;d=m.get(h).data.all_data;for(var f=0;f<d.length;f++)if(d[f].columns.key===o[w].key){l=d[f];break}c=o[w][c.name];if(l.operations!==undefined&&l.operations.row!==undefined&&l.operations.row.link!==undefined)if(c!==null&&c!==undefined&&c.toString().match(/<a\b[^>]*>.*<\/a>/)===null)c='<a style="display:block;" href="'+l.operations.row.link+'" class="listsnoul">'+
c+"</a>";a.push(c)});z.rows.push({key:o[w].key,cell:a})}jQuery("#"+m.get(h).jqgrid.id)[0].addJSONData(z)},m=function(){var g=[];return{add:function(h){g[h.getIdx()]=h},get:function(h){return g[h]!==undefined?g[h]:null},getAll:function(){return jQuery.extend({},g)},isExistent:function(h){return g[h]!==undefined?true:false}}}();F.loadList=function(g,h,p){p=parseInt(p,10);h=JSON.parse(h);if(isNaN(p)||p<0)throw new x.error.listIndexNotValid("List index "+p+" is not valid");if(m.isExistent(p))throw new x.error.indexAlreadyExistent("Index "+
p+" is already existent");new D(g,p,h.configuration,h.operations)}})();
