(function(){if(window.melange===undefined)throw new Error("Melange not loaded");var k=window.melange;k.graph=window.melange.graph=function(){return new k.graph};var i=k.logging.debugDecorator(k.graph);k.error.createErrors(["chartNotExistent","containerIsNull"]);i.allCharts={AreaChart:{public_name:"Area Chart",googlePackage:["areachart"]},BarChart:{public_name:"Bar Chart",googlePackage:["barchart"],default_options:{}},ColumnChart:{public_name:"Column Chart",googlePackage:["columnchart"],default_options:{}},
GeoMap:{public_name:"Geo Map",googlePackage:["geomap"],default_options:{}},ImageChartBar:{public_name:"Bar Chart (I)",googlePackage:["imagechart"],default_options:{cht:"bvs"}},ImageChartLine:{public_name:"Line Chart (I)",googlePackage:["imagechart"],default_options:{cht:"lc"}},ImageChartMap:{public_name:"Map Chart (I)",googlePackage:["imagechart"],default_options:{cht:"t",chtm:"world"}},ImageChartP:{public_name:"Pie Chart (I)",googlePackage:["imagechart"],default_options:{cht:"p"}},ImageChartP3:{public_name:"3D Pie Chart (I)",
googlePackage:["imagechart"],default_options:{cht:"p3"}},PieChart:{public_name:"Pie Chart",googlePackage:["piechart"],default_options:{is3D:true,pieJoinAngle:1}},ScatterChart:{public_name:"Scatter Chart",googlePackage:["scatterchart"],default_options:{}},Table:{public_name:"Table",googlePackage:["table"],default_options:{showRowNumber:true,page:"enable",pageSize:10}}};i.Widget=function(g,o){var r=this,p=["red","blue","green","yellow"],b=""+(new Date).getTime(),c={title:"Click to change me!",column:2,
place:null,style:{head:{background:"#765364"},content:{color:"white"}},movable:"true",visible:"true",virtual_statistic:null},e={type:"PieChart",options:{showRowNumber:true}},t={comment:"New chart",data:{}},v={},s=null,H={},u=[],w=null;this.setData=function(a){t.data=a};this.getData=function(){return t.data};this.setWidgetOptions=function(a){c=a};this.getWidgetOptions=function(){return c};this.setVisualizationTypes=function(a){H=a};this.setVirtualStatistics=function(a){v=a};var I=function(){c.place=
1+jQuery("#column3").find("li").size();c.style.head.background=p[Math.floor(Math.random()*p.length)];c.virtual_statistic=u[0];e.type="Table"},B=function(){u=[];jQuery.each(v,function(a){u.push(a)})};this.getId=function(){return b};var J=function(){jQuery.post("save_chart",{id:b,statistic_scope_path:g,statistic_link_id:o,widget_options:JSON.stringify(c),visualization_options:JSON.stringify(e)},function(){},"json")},x=function(){jQuery.post("update_chart",{data:JSON.stringify([{id:b,widget_options:JSON.stringify(c),
visualization_options:JSON.stringify(e)}])},function(){},"json")},C=function(a){var d=""+(new Date).getTime();jQuery.post("save_visualization",{id:d,statistic_scope_path:g,statistic_link_id:o,widget_options:JSON.stringify(c),visualization_options:JSON.stringify(e)},function(){a.call(r,d)},"json")},y=function(){jQuery.ajax({async:false,url:["/statistic/get_json_response/",g,"/",o].join(""),type:"POST",data:{statistic_name:s},success:function(a){t.data=a},dataType:"json"})},D=function(){var a="";jQuery.each(v[s],
function(d,h){a+="<option value='"+h+"'";if(h===e.type)a+=" selected='selected'";a+=[">",i.allCharts[h].public_name,"</option>"].join("")});return a},A=function(a,d){var h=/^(.*)\/show_dashboard/.exec(window.location.href)[1],m=/^\/(.*)\/show_dashboard/.exec(window.location.pathname)[1];jQuery("#export_"+b).remove();jQuery("#select_switch_visualization_"+b).after("<button id='export_"+b+"' value='Export'>Export</button>");var n=jQuery("#div_visualization_"+b).width(),q=jQuery("#div_visualization_"+
b).width();if(a.indexOf("ImageChart")>=0){if(a==="ImageChartP")q=Math.ceil(n/2);else if(a==="ImageChartP3")q=Math.ceil(n/3);d.chs=n+"x"+q;jQuery("#export_"+b).bind("click",{visualization_div:"#div_visualization_"+b},function(f){var l=jQuery(jQuery(f.data.visualization_div+" img")[0]).attr("src");C(function(z){alert(['If you want to copy the current image, paste this: \n <img src="',l,"\">\n\nIf you want to embed the visualization, paste this to your page: \n<script type='text/javascript' src='http://www.google.com/jsapi'><\/script>\nIf you want to embed the LIVE visualization,\n<script type='text/javascript' src='",
h,"/export?id=",b,"&amp;path=",encodeURIComponent(m),"&amp;div=myvisualization'><\/script>\n\notherwise if you want to embed the FREEZED visualization,\n<script type='text/javascript' src='",h,"/get_visualization?id=",z,"&amp;path=",encodeURIComponent(m),"&amp;div=myvisualization'><\/script>\n\nand put \n<div id='myvisualization'></div>\nwhere you want the visualization to appear"].join(""))})})}else{d.width=n;d.height=q;jQuery("#export_"+b).bind("click",function(){C(function(f){alert(["Paste this to your page: \n<script type='text/javascript' src='http://www.google.com/jsapi'><\/script>\nIf you want to embed the LIVE visualization,\n<script type='text/javascript' src='",
h,"/export?id=",b,"&amp;path=",encodeURIComponent(m),"&amp;div=myvisualization'><\/script>\n\notherwise if you want to embed the FREEZED visualization,\n<script type='text/javascript' src='",h,"/get_visualization?id=",f,"&amp;path=",encodeURIComponent(m),"&amp;div=myvisualization'><\/script>\n\nand put \n<div id='myvisualization'></div>\nwhere you want the visualization to appear"].join(""))})})}return new i[a]("div_visualization_"+b,t.data,d,function(){w.drawIntoContainer()})},K=function(){c.virtual_statistic=
s;e.type="Table";e.options=i.allCharts.Table.default_options||{};w=A("Table",i.allCharts.Table.default_options);x()},F=function(){var a=jQuery('<li class="widget">  <div class="widget-head">  </div>  <div class="widget-content">  </div></li>'),d=jQuery(a.find("[class=widget-head]")[0]);a.attr("id","widget-"+b);jQuery.each(c.style.head,function(f,l){a.css(f,l);f=jQuery("<h3>"+c.title+"</h3>");var z=function(j){c.title=j;x()};f.css({cursor:"text"});f.editable({submit:"ok",cancel:"cancel",onEdit:function(){var j=
this;j.find("button:contains('ok')").css({display:"none"});j.find("button:contains('cancel')").css({display:"none"});j.keydown(function(E){if(E.keyCode===13)j.find("button:contains('ok')").mouseup();else E.keyCode===27&&j.find("button:contains('c')").mouseup()})},onSubmit:function(j){z(j.current)}});d.html(f);d.append(jQuery('<a href="#" class="remove">CLOSE</a>').mousedown(function(j){j.stopPropagation()}).click(function(){confirm("This widget will be removed, ok?")&&jQuery(this).parents(".widget").animate({opacity:0},
function(){jQuery(this).wrap("<div/>").parent().slideUp(function(){jQuery(this).trigger({type:"widgetdeletion",widget:r}).remove()})})}));d.prepend(jQuery('<a href="#" class="collapse">COLLAPSE</a>').mousedown(function(j){j.stopPropagation()}).click(function(){if(c.visible==="true"){c.visible="false";jQuery(this).css({backgroundPosition:"-38px 0"}).parents(".widget").find(".widget-content").hide()}else{c.visible="true";jQuery(this).css({backgroundPosition:""}).parents(".widget").find(".widget-content").show()}x()}))});
var h=jQuery(a.find("[class=widget-content]")[0]),m="";if(u.length>1){var n="";jQuery.each(u,function(f,l){n+="<option value='"+l+"'";if(l===c.virtual_statistic)n+=" selected='selected'";n+=">"+l+"</option>"});m+=["<div id='div_switch_statistic_",b,"'>  Show statistic:   <select id='select_switch_statistic_",b,"'> ",n,"  </select></div>"].join("")}var q=D();m+=["<div id='div_switch_visualization_",b,"'>  Show visualization:   <select id='select_switch_visualization_",b,"'> ",q,"  </select></div>"].join("");
m+="<div id='div_visualization_"+b+"'></div>";h.html(m);Boolean(c.movable)===true&&d.css({cursor:"move"}).mousedown(function(){jQuery(this).css({width:""});jQuery(this).parent().css({width:jQuery(this).parent().width()+"px"})}).mouseup(function(){jQuery(this).parent().hasClass("dragging")?jQuery(".column").sortable("disable").change():jQuery(this).parent().css({width:""})});jQuery("#column"+c.column).append(a);if(c.visible==="false"){h.hide();h.parents(".widget").find(".widget-head").css({backgroundPosition:"-38px 0"})}h=
jQuery(".column").sortable("option","items");h+=",#"+b;jQuery("#select_switch_statistic_"+b).bind("change",function(f){s=f.target.value;y();K(s);q=D();jQuery("#select_switch_visualization_"+b).replaceWith(["<select id='select_switch_visualization_",b,"'>",q,"</select>"].join(""));jQuery("#select_switch_visualization_"+b).bind("change",{current_widget:r},function(l){l.data.current_widget.switchVisualizationTo(l.target.value)})});jQuery("#select_switch_visualization_"+b).bind("change",{current_widget:r},
function(f){f.data.current_widget.switchVisualizationTo(f.target.value)});w=A(e.type,e.options)};this.switchVisualizationTo=function(a){e.type=a;e.options=i.allCharts[a].default_options||{};w=A(a,i.allCharts[a].default_options);x()};this.initialize=function(a){this.setVirtualStatistics(a);B();I();s=u[0];y();F();J()};this.createFromJSON=function(a,d){b=a;jQuery.extend(c,d.widget_options);jQuery.extend(e,d.visualization_options);jQuery.extend(v,d.virtual_statistics);B();o=d.statistic_link_id;g=d.statistic_scope_path;
s=d.current_statistic;y();F()}};var G=function(g,o,r){this.packages={packages:[]};this.chart_data={container:g,data:o||{},options:r||{}};this.visualization=null;this.getData=function(){return k.clone(this.chart_data.data)};this.getOptions=function(){return k.clone(this.chart_data.options)};this._drawIntoContainer=function(){throw new k.error.notImplementedByChildClass("_drawIntoContainer should be implemented by a child class");};this.drawIntoContainer=function(p){if(p=p||this.chart_data.container)this._drawIntoContainer(p);
else throw new k.error.containerIsNull(["container should be a valid id, ",p," passed instead"].join(""));}};jQuery.each(i.allCharts,function(g,o){i[g]=function(r,p,b,c){G.apply(this,arguments);this.packages.packages=o.googlePackage;k.loadGoogleApi("visualization","1",this.packages,c);this._drawIntoContainer=function(e){jQuery("#"+e).html("");var t=new google.visualization.DataTable(this.chart_data.data,0.6);if(g.indexOf("ImageChart")>=0)g="ImageChart";this.visualization=new google.visualization[g](document.getElementById(e));
this.visualization.draw(t,this.chart_data.options)}};i[g].prototype=new G;i[g].prototype.constructor=i[g]})})();
