(function(){function C(h,i,p,n){var b=this,x={datatype:D,viewrecords:true},t={edit:false,add:false,del:false,afterRefresh:function(){b.refreshData();b.jqgrid.object.trigger("reloadGrid")}};h=h;i=i;this.configuration=p;this.operations=n;this.jqgrid={id:null,object:null,options:null,last_selected_row:null,editable_columns:[],dirty_fields:{},pager:{id:null,options:null}};this.data={data:[],all_data:[],filtered_data:null};var u={enableDisableButtons:function(a){return function(f){function d(m){var c=
jQuery("#"+a.jqgrid.id).jqGrid("getRowData",m),e=s.from(a.data.all_data).equals("columns.key",c.key).select()[0];if(a.jqgrid.dirty_fields[c.key]===undefined)a.jqgrid.dirty_fields[c.key]=[];var r=[],q=[];jQuery.each(c,function(o,l){l!=e.columns[o]?r.push(o):q.push(o)});jQuery.each(r,function(o,l){jQuery.inArray(l,a.jqgrid.dirty_fields[c.key])===-1&&a.jqgrid.dirty_fields[c.key].push(l)});jQuery.each(q,function(o,l){o=jQuery.inArray(l,a.jqgrid.dirty_fields[c.key]);o!==-1&&a.jqgrid.dirty_fields[c.key].splice(o,
1)});a.jqgrid.dirty_fields[c.key].length===0&&delete a.jqgrid.dirty_fields[c.key];jQuery.each(a.operations.buttons,function(o,l){if(l.type==="post_edit"){o=jQuery("#"+a.jqgrid.id+"_buttonOp_"+l.id);B(a.jqgrid.dirty_fields)?o.attr("disabled","disabled"):o.removeAttr("disabled")}})}var j=a.jqgrid.object.jqGrid("getGridParam","multiselect")?"selarrrow":"selrow",g=a.jqgrid.object.jqGrid("getGridParam",j);if(!g instanceof Array)g=[g];if(g.length===1)if(f&&f!==a.jqgrid.last_selected_row){jQuery("#"+a.jqgrid.id).restoreRow(a.jqgrid.last_selected_row);
jQuery("#"+a.jqgrid.id).jqGrid("editRow",f,true,null,null,"clientArray",null,d);a.jqgrid.last_selected_row=f}jQuery.each(a.operations.buttons,function(m,c){m=jQuery("#"+a.jqgrid.id+"_buttonOp_"+c.id);if(c.type!=="post_edit")if(g.length>=c.real_bounds[0]&&g.length<=c.real_bounds[1]){m.removeAttr("disabled");if(c.real_bounds[0]===1&&c.real_bounds[1]===1&&m.data("melange")!==undefined){var e=a.jqgrid.object.jqGrid("getRowData",g[0]);e=s.from(a.data.all_data).equals("columns.key",e.key).select()[0];var r=
m.data("melange").click;m.click(r(e.operations.buttons[c.id].link));m.attr("value",e.operations.buttons[c.id].caption)}}else m.attr("disabled","disabled")})}}(b),global_button_functions:{redirect_simple:function(a){return a.new_window?function(){window.open(a.link)}:function(){window.location.href=a.link}},redirect_custom:function(a){return function(f){return a.new_window?function(){window.open(f)}:function(){window.location.href=f}}},post:function(a){return function(){var f=k.get(a.idx).jqgrid.object.jqGrid("getGridParam",
"multiselect")?"selarrrow":"selrow";f=k.get(a.idx).jqgrid.object.jqGrid("getGridParam",f);f instanceof Array||(f=f===null?[]:[f]);var d=[];if(!(f.length<a.real_bounds[0]||f.length>a.real_bounds[1])){jQuery.each(f,function(j,g){var m=jQuery("#"+k.get(a.idx).jqgrid.id).jqGrid("getRowData",g);s.from(k.get(a.idx).all_data).equals("columns.key",m.key).select();var c={};jQuery.each(a.keys,function(e,r){e=m[r];if(jQuery(e).hasClass("listsnoul"))e=/^<a\b[^>]*>(.*?)<\/a>$/.exec(e)[1];c[r]=e});d.push(c)});
if(a.url==="")a.url=window.location.href;jQuery.post(a.url,{xsrf_token:window.xsrf_token,idx:a.idx,button_id:a.button_id,data:JSON.stringify(d)},function(j){if(a.redirect=="true")try{var g=JSON.parse(j);if(g.data.url!==undefined)window.location.href=g.data.url}catch(m){}j=parseInt(a.refresh,10);if(!isNaN(j)){k.get(j).refreshData();jQuery("#"+k.get(j).jqgrid.id).trigger("reloadGrid")}if(a.refresh=="current"){k.get(a.idx).refreshData();jQuery("#"+k.get(a.idx).jqgrid.id).trigger("reloadGrid")}else if(a.refresh==
"all"){j=k.getAll();jQuery.each(j,function(c,e){e.refreshData();jQuery("#"+k.get(c).jqgrid.id).trigger("reloadGrid")})}})}}},post_edit:function(a){return function(){var f=k.get(a.idx).jqgrid,d={};if(!(f.editable_columns.length===0&&B(f.dirty_fields))){for(var j=f.object.jqGrid("getGridParam","records"),g=1;g<=j;g++){var m=jQuery("#"+f.id).jqGrid("getRowData",g);if(f.dirty_fields[m.key]!==undefined){d[m.key]={};jQuery.each(f.dirty_fields[m.key],function(c,e){d[m.key][e]=m[e]})}}if(a.url==="")a.url=
window.location.href;jQuery.post(a.url,{xsrf_token:window.xsrf_token,idx:a.idx,button_id:a.button_id,data:JSON.stringify(d)},function(c){if(a.redirect=="true")try{var e=JSON.parse(c);if(e.data.url!==undefined)window.location.href=e.data.url}catch(r){}c=parseInt(a.refresh,10);if(!isNaN(c)){k.get(c).refreshData();jQuery("#"+k.get(c).jqgrid.id).trigger("reloadGrid")}if(a.refresh=="current"){k.get(a.idx).refreshData();jQuery("#"+k.get(a.idx).jqgrid.id).trigger("reloadGrid")}else if(a.refresh=="all"){c=
k.getAll();jQuery.each(c,function(q,o){o.refreshData();jQuery("#"+k.get(q).jqgrid.id).trigger("reloadGrid")})}})}}}},row_functions:{redirect_custom:function(a){return function(f,d){return a.new_window||d.which===2||d.which===1&&d.ctrlKey?function(){window.open(f)}:function(){window.location.href=f}}}}},A=function(){jQuery("#"+h).replaceWith(['<p id="temporary_list_placeholder_',i,'"></p>','<table id="'+b.jqgrid.id+'"',' cellpadding="0" cellspacing="0"></table>','<div id="'+b.jqgrid.pager.id+'"',' style="text-align:center"></div>'].join(""))},
y=function(){var a="",f=0,d=function(){var j="?";if(window.location.href.indexOf("?")!==-1)j="&";jQuery.ajax({async:true,cache:false,url:[window.location.href,j,"fmt=json&limit=150",a===""?"":"&start="+a,"&idx=",i].join(""),timeout:6E4,tryCount:1,retryLimit:5,error:function(g){if(g.status==500){this.tryCount++;if(this.tryCount<=this.retryLimit)jQuery.ajax(this);else{jQuery("#temporary_list_placeholder_"+i).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');
jQuery("#load_"+b.jqgrid.id).hide()}}else{jQuery("#temporary_list_placeholder_"+i).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');jQuery("#load_"+b.jqgrid.id).hide()}},success:function(g){var m=g.next==="done";if(g.data[a]!==undefined){if(b.configuration===null)b.configuration=g.configuration;if(b.operations===null)b.operations=g.operations;jQuery.each(g.data[a],function(){b.data.data.push(this.columns);b.data.all_data.push(this)});
b.jqgrid.object===null?v():b.jqgrid.object.trigger("reloadGrid");if(m){a=g.next;setTimeout(d,100);f++}else{jQuery("#temporary_list_placeholder_"+i).remove();jQuery("#load_"+b.jqgrid.id).hide()}}if(m){jQuery("#temporary_list_placeholder_"+i).remove();jQuery("#load_"+b.jqgrid.id).hide();jQuery("#"+b.jqgrid.id)[0].triggerToolbar();jQuery.each(b.configuration.colModel,function(c,e){e.editable!==undefined&&e.editable===true&&b.jqgrid.editable_columns.push(e.name)});jQuery("#t_"+b.jqgrid.id).children().remove();
b.operations!==undefined&&b.operations.buttons!==undefined&&jQuery.each(b.operations.buttons,function(c,e){c=b.jqgrid.id+"_buttonOp_"+e.id;jQuery("#t_"+b.jqgrid.id).append("<input type='button' value='"+e.caption+"' style='float:left' id='"+c+"'/>");e.parameters.idx=i;if(e.type!=="post_edit"){e.real_bounds=e.bounds;var r=e.real_bounds.indexOf("all");if(r!==-1)e.real_bounds[r]=b.jqgrid.object.jqGrid("getGridParam","records");e.parameters.real_bounds=e.real_bounds}if(e.type==="post_edit"||e.real_bounds[0]>
0)jQuery("#"+c).attr("disabled","disabled");e.parameters.button_id=e.id;jQuery("#"+c).click(u.global_button_functions[e.type](e.parameters));e.type=="redirect_custom"&&jQuery("#"+c).data("melange",{click:u.global_button_functions[e.type](e.parameters)})});jQuery("#t_"+b.jqgrid.id).css("padding-bottom","3px");jQuery("#t_"+b.jqgrid.id).append("<input type='button' value='CSV Export' style='float:right;' id='csvexport_"+b.jqgrid.id+"'/>");jQuery("#csvexport_"+b.jqgrid.id).button();jQuery("#csvexport_"+
b.jqgrid.id).click(function(){var c=[];c[0]=[];if(b.data.data[0]!==undefined||b.data.filtered_data[0]!==undefined){var e=b.data.filtered_data||b.data.data;jQuery.each(b.configuration.colNames,function(q,o){q=o;q=q.replace(/\"|&quot;|&#34;/g,'""');if(q.indexOf(",")!==-1||q.indexOf('"')!==-1||q.indexOf("\r\n")!==-1)q='"'+q+'"';c[0].push(q)});c[0]=c[0].join(",");var r=[];jQuery.each(b.configuration.colModel,function(q,o){r.push(o.name)});jQuery.each(e,function(q,o){c[c.length]=[];jQuery.each(r,function(l,
z){l=o[z];if(l===null)l="";if(l===undefined)l="";l=l.toString();z=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(l);if(z!==null)l=z[1];l=l.replace(/\"|&quot;|&#34;/g,'""');if(l.indexOf(",")!==-1||l.indexOf('"')!==-1||l.indexOf("\r\n")!==-1)l='"'+l+'"';c[c.length-1].push(l)});c[c.length-1]=c[c.length-1].join(",")});c=c.join("\r\n");jQuery("#csv_dialog").remove();jQuery("body").append(["<div id='csv_dialog' style='display:none'>  <h3>Now you can copy and paste CSV data from the text area to a new file:</h3>  <textarea style='width:450px;height:250px'>",
c,"</textarea></div>"].join(""));jQuery("#csv_dialog").dialog({height:420,width:500,modal:true,buttons:{Close:function(){jQuery(this).dialog("close")}}})}});jQuery("#t_"+b.jqgrid.id).append("<div style='float:right;margin-right:4px;'><input type='checkbox' id='regexp_"+b.jqgrid.id+"'/>RegExp Search</div>");jQuery("#regexp_"+b.jqgrid.id).click(function(){jQuery("#"+b.jqgrid.id).jqGrid().trigger("reloadGrid")});g=jQuery.Event("melange_list_loaded");g.list_object=b;b.jqgrid.object.trigger(g)}}})};setTimeout(d,
100)};this.refreshData=function(){b.data={data:[],all_data:[],filtered_data:null};y()};var v=function(){var a=jQuery.extend(b.configuration,{postData:{my_index:i},onSelectAll:u.enableDisableButtons,onSelectRow:u.enableDisableButtons}),f={caption:"",buttonicon:"ui-icon-calculator",onClickButton:function(){jQuery("#"+b.jqgrid.id).setColumns({colnameview:false,jqModal:true,ShrinkToFit:true});return false},position:"last",title:"Show/Hide Columns",cursor:"pointer"};jQuery("#"+b.jqgrid.id).jqGrid(jQuery.extend(b.jqgrid.options,
a)).jqGrid("navGrid","#"+b.jqgrid.pager.id,b.jqgrid.pager.options,{},{},{},{closeAfterSearch:true,multipleSearch:true},{}).jqGrid("navButtonAdd","#"+b.jqgrid.pager.id,f);jQuery("#"+b.jqgrid.id).jqGrid("filterToolbar",{});jQuery("#load_"+b.jqgrid.id).closest("div").css("line-height","100%");jQuery("#load_"+b.jqgrid.id).html("<img src='/soc/content/images/jqgrid_loading.gif'></img>");jQuery("#load_"+b.jqgrid.id).show();b.jqgrid.object=jQuery("#"+b.jqgrid.id)};this.getDiv=function(){return h};this.getIdx=
function(){return i};(function(){jQuery(function(){if(jQuery("#"+h).length===0)throw new w.error.divNotExistent("Div "+h+" is not existent");b.jqgrid.id="jqgrid_"+h;b.jqgrid.pager.id="jqgrid_pager_"+h;b.jqgrid.options=jQuery.extend(x,{pager:"#"+b.jqgrid.pager.id});b.jqgrid.pager.options=t;k.add(b);A();v();y()})})()}if(window.melange===undefined)throw new Error("Melange not loaded");var w=window.melange;if(window.jLinq===undefined)throw new Error("jLinq not loaded");var s=window.jLinq;w.list=window.melange.list=
function(){return new w.list};var E=w.logging.debugDecorator(w.list);w.error.createErrors(["listIndexNotValid","divNotExistent","indexAlreadyExistent"]);var B=function(h){for(var i in h)return false;return true},D=function(h){var i=h.my_index,p=k.get(i).data.data,n=p,b="",x={eq:{method:"equals",not:false},ne:{method:"equals",not:true},lt:{method:"less",not:false},le:{method:"lessEquals",not:false},gt:{method:"greater",not:false},ge:{method:"greaterEquals",not:false},bw:{method:"startsWith",not:false},
bn:{method:"startsWith",not:true},ew:{method:"endsWith",not:false},en:{method:"endsWith",not:true},cn:{method:"contains",not:false},nc:{method:"contains",not:true},"in":{method:"match",not:false},ni:{method:"match",not:true}};if(h._search&&h.filters){var t=JSON.parse(h.filters);if(t.rules[0].data!==""){b=t.groupOp;if(b==="OR")n={};jQuery.each(t.rules,function(f,d){if(d.op==="in"||d.op==="ni")d.data=d.data.split(",").join("|");n=x[d.op].not?b==="OR"?s.from(n).union(s.from(p).not()[x[d.op].method](d.field,
d.data).select()).select():s.from(n).not()[x[d.op].method](d.field,d.data).select():b==="OR"?s.from(n).union(s.from(p)[x[d.op].method](d.field,d.data).select()).select():s.from(n)[x[d.op].method](d.field,d.data).select()})}}else p[0]!==undefined&&jQuery.each(p[0],function(f){if(h[f]!==undefined){var d=jQuery("#regexp_"+k.get(i).jqgrid.id).is(":checked"),j=false;jQuery.each(k.get(i).configuration.colModel,function(g,m){if(m.editoptions!==undefined&&f===m.name)j=true});n=d||j?s.from(n).match(f,h[f]).select():
s.from(n).contains(f,h[f]).select()}});var u=h.sidx;t=h.sord;jQuery.each(k.get(i).configuration.colModel,function(f,d){if(d.name===u&&(d.sorttype==="integer"||d.sorttype==="int"))jQuery.each(n,function(j,g){j=parseInt(g[u],10);isNaN(j)||(g[u]=j)})});t=t==="asc"?"":"-";if(n.length>0)n=s.from(n).ignoreCase().orderBy(t+u).select();k.get(i).data.filtered_data=n;if(h.rows===-1)h.rows=k.get(i).data.filtered_data.length;t=(h.page-1)*h.rows;for(var A=h.page*h.rows-1,y={page:h.page,total:n.length===0?0:Math.ceil(n.length/
h.rows),records:n.length,rows:[]},v=t;v<=A;v++)if(n[v]!==undefined){var a=[];p[0]!==undefined&&jQuery.each(k.get(i).configuration.colModel,function(f,d){var j;f=k.get(i).data.all_data;for(var g=0;g<f.length;g++)if(f[g].columns.key===n[v].key){j=f[g];break}d=n[v][d.name];if(j.operations!==undefined&&j.operations.row!==undefined&&j.operations.row.link!==undefined)if(d!==null&&d!==undefined&&d.toString().match(/<a\b[^>]*>.*<\/a>/)===null)d='<a style="display:block;" href="'+j.operations.row.link+'" class="listsnoul">'+
d+"</a>";a.push(d)});y.rows.push({key:n[v].key,cell:a})}jQuery("#"+k.get(i).jqgrid.id)[0].addJSONData(y)},k=function(){var h=[];return{add:function(i){h[i.getIdx()]=i},get:function(i){return h[i]!==undefined?h[i]:null},getAll:function(){return jQuery.extend({},h)},isExistent:function(i){return h[i]!==undefined?true:false}}}();E.loadList=function(h,i,p){p=parseInt(p,10);i=JSON.parse(i);if(isNaN(p)||p<0)throw new w.error.listIndexNotValid("List index "+p+" is not valid");if(k.isExistent(p))throw new w.error.indexAlreadyExistent("Index "+
p+" is already existent");new C(h,p,i.configuration,i.operations)}})();
